### ISSUE TITLE
referenceerror global is not defined

### ISSUE THREAD

**Issue by diamo1213** [cupcakearmy/occulto#2]
use the modul in angular 9 leads to 'referenceerror global is not defined'

**Comment by cupcakearmy** [comment]
I guess you mean inside the browser right? It is currently not supported, I wanted to look into the web crypto api to add the browser equivalent to the api.

**Comment by diamo1213** [comment]
@cupcakearmy yeah, browser crys about that

**Comment by cupcakearmy** [comment]
I will look at this this evening (europe time). Support is more limited though, only aes as ciphers

https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/encrypt and hashes are only sha 1 to 512. rsa seems like it is fully supported

**Comment by cupcakearmy** [comment]
see issue #1

**Comment by cupcakearmy** [comment]
Closing this in favor of #1. I've tried a few things the last days and it's not super trivial unfortunately. the APIs are quite different between the node and web crypto.
